services:
  db:
    image: postgres:17.5
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Bogota
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data 